# VARIABLES
CC		= gcc
CFLAGS		= -g -O2 -static -static-libgcc
DEFS		= 
#DEFS		= -DTRACE

#MACRO DEFINITIONS




# Linking information
simpleshell : simpleshell.c
	${CC} $ ${CFLAGS} ${DEFS} simpleshell.c -o $@




# make all
all:
	simpleshell

# clean object files
clean:
	rm simpleshell
